version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ../backend:/var/www/backend
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    volumes:
      - ../:/var/www
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=assuranceMap
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data